version: "3.8"

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    ports:
      - 80:5000
    volumes:
      - .:/app
    command: npm start
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
    driver: local